name = "CacheVariables"
uuid = "9a355d7c-ffe9-11e8-019f-21dae27d1722"
authors = ["David Hong <dahong@umich.edu>"]
version = "0.1.0"

[deps]
BSON = "fbb218c0-5317-5bc6-957e-2ee96dd4b1f0"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]

[compat]
julia = "1.0"
BSON = "0.2.3"
